### ISSUE TITLE
Possible Underestimation of Channel Transfer Time Calculation

### ISSUE THREAD

**Issue by ABC12345anouys** [wangyuyue/SimpySSD#1]
Hello,
I’ve been reviewing your code and noticed a potential issue regarding the calculation of channel transfer time. In the transfer_time method, you used the following formula:
def transfer_time(self, cmd):
    return cmd.data_sz / self.bw 
 Here, data_sz is approximately 4KB (4000 bytes), and bw is 800 Mbps. This calculation results in a transfer time of 5 microseconds. 
 However, when calculating the time it takes to transfer 4KB at a bandwidth of 800 Mbps, my calculations suggest that it should be around 40 microseconds.
  It seems that the channel transfer time may be underestimated in your implementation. I would appreciate it if you could review my understanding of this issue.
Thank you!
![image](https://github.com/user-attachments/assets/10955ca0-1482-4a40-93a3-38e8b33689dd)

**Comment by wangyuyue** [comment]
Hi, the mbps here means megabyte per second, not megabit. Sorry for the confusion it makes.
So the latency is calculated as 4,000 byte / 800,000,000 byte/s  * 1,000,000 us/s = 5 us.
Hope this solves your issue.
